Update publications.md
klee/klee.github.io pull request #332
Opened 2022-06-30 02:19 UTC by rshariffdeen

add patch transplantation work using Klee

2022-06-30 08:21 UTC, 251 requested changes
Thanks for the PR! Please have a look at my comments.

2022-06-30 08:21 UTC, 251 commented on publications.md
> +  Ridwan Shariffdeen, Shin Hwei Tan, Mingyuan Gao, Abhik Roychoudhury
You need to add two spaces at the end of this line and the next one, otherwise there is no line-break.

2022-06-30 08:21 UTC, 251 commented on publications.md
> +  December 2020
Could you please change it to "January 2021" as in the acm link (and keep the position in the publication list)?

2022-06-30 08:59 UTC, 251 commented on publications.md
> +  Ridwan Shariffdeen, Shin Hwei Tan, Mingyuan Gao, Abhik Roychoudhury
Note: the spaces are still missing.

2022-06-30 12:45 UTC, 251 commented on publications.md
> +  Ridwan Shariffdeen, Shin Hwei Tan, Mingyuan Gao, Abhik Roychoudhury
Two more things:
1. Remove the spaces from the last line (the one with the link); sorry for the annoying markup format.
2. Could you please squash the commits ([HOWTO: squashing](https://github.com/openedx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes=))?

2022-07-03 20:38 UTC, 251 commented
@rshariffdeen 

Are you still interested in this PR? Otherwise I can just add the paper.

2022-07-03 20:46 UTC, rshariffdeen commented
I made a new PR, will close this one

2022-07-03 20:46 UTC, closed without merging